#!/usr/bin/env python3
"""Generate built-in i18n lookup tables and CJK glyph subsets."""

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path

import i18n_catalog


DEFAULT_UI_FONT = (
    Path(__file__).resolve().parents[1]
    / "assets" / "fonts" / "NotoSansSC-VariableFont_wght.ttf"
)
DEFAULT_CJK_FALLBACK_FONT = (
    Path(__file__).resolve().parents[1]
    / "assets" / "fonts" / "NotoSansSC-VariableFont_wght.ttf"
)
DEFAULT_TITLE_FONT = DEFAULT_UI_FONT
DEFAULT_BODY_FONT = DEFAULT_UI_FONT

# ── 字库尺寸（spec §2 字体阶梯）──────────────────────────────────────
#
# 这些数字曾经只活在某次手敲的命令行里，脚本自己的默认值还停在 320×240 时代
# 的 16/8/12 px。于是「改完 catalog 重跑一遍脚本」这个本该无脑的动作，会把三
# 套 CJK 字库**静默降级**回 spec §2 明令禁止的档位（「低于 18 px 一律禁止出
# 现」），而且降级后照样编译、照样出图，只是屏上汉字全变小。
#
# 所以默认值就是真值：L30 / M26 / S21，与 3afa39c 重生成时用的一致。改档位请
# 改这里，不要再靠命令行参数——命令行会随着终端历史一起消失。
DEFAULT_TITLE_CELL = 30       # 页面标题档
DEFAULT_TITLE_PT = 29
DEFAULT_BODY_CELL = 26        # 正文主力档
DEFAULT_BODY_PT = 25
DEFAULT_UI_BODY_H = 21        # 标签档（UI 变宽字库）
DEFAULT_UI_BODY_PT = 20
DEFAULT_UI_ASCII_W = 8
DEFAULT_UI_WIDE_W = 12


def enum_label(prefix: str, name: str) -> str:
    return f"{prefix}_{name.upper()}"


def c_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )


def validate_catalog(strings: list[tuple[str, dict[str, str]]]) -> None:
    seen: set[str] = set()
    lang_set = set(i18n_catalog.LANGS)
    for text_id, translations in strings:
        if text_id in seen:
            raise ValueError(f"duplicate text id: {text_id}")
        seen.add(text_id)
        if set(translations) != lang_set:
            raise ValueError(f"{text_id} languages {sorted(translations)} != {sorted(lang_set)}")
        for lang, text in translations.items():
            if not text:
                raise ValueError(f"{text_id}.{lang} is empty")


def collect_cjk_codepoints(strings: list[tuple[str, dict[str, str]]]) -> set[int]:
    return {
        ord(ch)
        for _, translations in strings
        for text in translations.values()
        for ch in text
        if ord(ch) > 0x7F
    }


def collect_ui_codepoints(strings: list[tuple[str, dict[str, str]]]) -> set[int]:
    codes = set(range(0x20, 0x7F))
    codes.add(0x00B0)
    codes.update(collect_cjk_codepoints(strings))
    return codes


def ui_glyph_width(code: int) -> int:
    return DEFAULT_UI_ASCII_W if code <= 0x7F or code == 0x00B0 else DEFAULT_UI_WIDE_W


def default_font_chain(primary: Path | None = None,
                       fallback: Path | None = None) -> list[Path]:
    primary = primary or DEFAULT_UI_FONT
    fallback = fallback or DEFAULT_CJK_FALLBACK_FONT
    fonts = [primary]
    if fallback != primary:
        fonts.append(fallback)
    return fonts


def emit_i18n_header(path: Path, strings: list[tuple[str, dict[str, str]]]) -> None:
    lines = [
        "/* Generated by firmware/scripts/gen_i18n_assets.py. */",
        "#pragma once",
        "",
        "typedef enum {",
    ]
    for idx, lang in enumerate(i18n_catalog.LANGS):
        lines.append(f"    PK_LANG_{lang.upper()} = {idx},")
    lines.extend(
        [
            "    PK_LANG_COUNT,",
            "} pk_lang_t;",
            "",
            "typedef enum {",
        ]
    )
    for idx, (text_id, _) in enumerate(strings):
        lines.append(f"    {enum_label('PK_TR', text_id)} = {idx},")
    lines.extend(
        [
            "    PK_TR_COUNT,",
            "} pk_tr_id_t;",
            "",
            "const char *pk_i18n_catalog_text(pk_lang_t lang, pk_tr_id_t id);",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_i18n_source(path: Path, strings: list[tuple[str, dict[str, str]]]) -> None:
    lines = [
        "/* Generated by firmware/scripts/gen_i18n_assets.py. */",
        '#include "i18n_catalog.h"',
        "",
        "static const char *const s_text[PK_LANG_COUNT][PK_TR_COUNT] = {",
    ]
    for lang in i18n_catalog.LANGS:
        lines.append(f"    [PK_LANG_{lang.upper()}] = {{")
        for text_id, translations in strings:
            lines.append(
                f'        [{enum_label("PK_TR", text_id)}] = "{c_string(translations[lang])}",'
            )
        lines.append("    },")
    lines.extend(
        [
            "};",
            "",
            "const char *pk_i18n_catalog_text(pk_lang_t lang, pk_tr_id_t id)",
            "{",
            "    if (lang < 0 || lang >= PK_LANG_COUNT) lang = PK_LANG_EN;",
            "    if (id < 0 || id >= PK_TR_COUNT) return \"?\";",
            "    const char *text = s_text[lang][id];",
            "    return text ? text : s_text[PK_LANG_EN][id];",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def render_glyph(
    magick: str,
    font: Path,
    point_size: int,
    width: int,
    height: int,
    code: int,
) -> bytes:
    if code == 0x20:
        return bytes(width * height)

    with tempfile.TemporaryDirectory() as tmp:
        label_path = Path(tmp) / "glyph.txt"
        raw_path = Path(tmp) / "glyph.gray"
        label_path.write_text(chr(code), encoding="utf-8")
        subprocess.run(
            [
                magick,
                "-background",
                "black",
                "-fill",
                "white",
                "-font",
                str(font),
                "-pointsize",
                str(point_size),
                "-gravity",
                "center",
                "-size",
                f"{width}x{height}",
                f"label:@{label_path}",
                "-depth",
                "8",
                f"gray:{raw_path}",
            ],
            check=True,
        )
        gray = raw_path.read_bytes()
    expected = width * height
    if len(gray) != expected:
        raise RuntimeError(f"glyph U+{code:04X} produced {len(gray)} bytes, expected {expected}")
    return gray


def glyph_has_ink(gray: bytes) -> bool:
    return any(gray)


def render_glyph_with_fallback(
    magick: str,
    fonts: list[Path],
    point_size: int,
    width: int,
    height: int,
    code: int,
) -> bytes:
    if code == 0x20:
        return bytes(width * height)

    last_gray = bytes(width * height)
    for font in fonts:
        gray = render_glyph(magick, font, point_size, width, height, code)
        if glyph_has_ink(gray):
            return gray
        last_gray = gray
    return last_gray


def pack_4bpp(gray: bytes) -> bytes:
    packed = bytearray()
    for i in range(0, len(gray), 2):
        hi = min(15, (gray[i] + 8) // 17)
        lo = 0
        if i + 1 < len(gray):
            lo = min(15, (gray[i + 1] + 8) // 17)
        packed.append((hi << 4) | lo)
    return bytes(packed)


def normalize_glyph_alpha(gray: bytes) -> bytes:
    """Stretch a glyph mask so its strongest ink reaches full opacity.

    Tiny variable-font glyphs can render with a low maximum gray value
    when their strokes land between pixels. Packing that raw mask makes
    the firmware blend the stroke body at only 25-50% alpha. Normalizing
    per glyph keeps anti-aliased edge levels while making the main stroke
    opaque on the LCD.
    """
    max_v = max(gray) if gray else 0
    if max_v <= 0 or max_v == 255:
        return gray
    return bytes((v * 255 + max_v // 2) // max_v if v else 0 for v in gray)


def pack_ui_4bpp(gray: bytes) -> bytes:
    return pack_4bpp(normalize_glyph_alpha(gray))


def pack_readable_4bpp(gray: bytes) -> bytes:
    return pack_ui_4bpp(gray)


def glyph_bytes_4bpp(width: int, height: int) -> int:
    return (width * height + 1) // 2


def emit_cjk_header(path: Path, width: int, height: int,
                    macro_prefix: str, glyph_func: str) -> None:
    path.write_text(
        f"""/* Generated by firmware/scripts/gen_i18n_assets.py. */
#pragma once

#include <stdint.h>

#define {macro_prefix}_CELL_W {width}
#define {macro_prefix}_CELL_H {height}
#define {macro_prefix}_GLYPH_BYTES {glyph_bytes_4bpp(width, height)}

const uint8_t *{glyph_func}(uint32_t code);
""",
        encoding="utf-8",
    )


def emit_cjk_source(
    path: Path,
    header_name: str,
    codes: list[int],
    bitmaps: list[bytes],
    macro_prefix: str,
    glyph_func: str,
) -> None:
    lines = [
        "/* Generated by firmware/scripts/gen_i18n_assets.py.",
        " * Glyphs are 4bpp alpha masks, two pixels per byte.",
        " */",
        f'#include "{header_name}"',
        "",
        "#include <stddef.h>",
        "",
        f"static const uint32_t s_cjk_codes[{len(codes)}] = {{",
    ]
    for code in codes:
        lines.append(f"    0x{code:04X}, /* {chr(code)} */")
    lines.extend(["};", "", f"static const uint8_t s_cjk_bitmaps[{len(codes)}][{macro_prefix}_GLYPH_BYTES] = {{"])
    for code, bitmap in zip(codes, bitmaps):
        lines.append(f"    /* U+{code:04X} {chr(code)} */")
        lines.append("    {")
        for i in range(0, len(bitmap), 12):
            lines.append("        " + ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 12]) + ",")
        lines.append("    },")
    lines.extend(
        [
            "};",
            "",
            f"const uint8_t *{glyph_func}(uint32_t code)",
            "{",
            "    for (size_t i = 0; i < sizeof(s_cjk_codes) / sizeof(s_cjk_codes[0]); ++i) {",
            "        if (s_cjk_codes[i] == code) return s_cjk_bitmaps[i];",
            "    }",
            "    return NULL;",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def threshold_4bpp(gray: bytes, threshold: int = 48) -> bytes:
    """Pack a solid bitmap mask into the existing 4bpp glyph container."""
    packed = bytearray()
    for i in range(0, len(gray), 2):
        hi = 0x0F if gray[i] >= threshold else 0x00
        lo = 0x00
        if i + 1 < len(gray):
            lo = 0x0F if gray[i + 1] >= threshold else 0x00
        packed.append((hi << 4) | lo)
    return bytes(packed)


def emit_ui_font_header(path: Path, height: int, max_w: int,
                        glyph_func: str) -> None:
    path.write_text(
        f"""/* Generated by firmware/scripts/gen_i18n_assets.py. */
#pragma once

#include <stdint.h>

#define PK_TEXT_CJK_UI_CELL_H {height}
#define PK_TEXT_CJK_UI_MAX_W {max_w}

const uint8_t *{glyph_func}(uint32_t code, uint8_t *width);
""",
        encoding="utf-8",
    )


def emit_ui_font_source(
    path: Path,
    header_name: str,
    codes: list[int],
    widths: list[int],
    bitmaps: list[bytes],
    glyph_func: str,
) -> None:
    offsets: list[int] = []
    cursor = 0
    for bitmap in bitmaps:
        offsets.append(cursor)
        cursor += len(bitmap)

    lines = [
        "/* Generated by firmware/scripts/gen_i18n_assets.py.",
        " * UI glyphs are 4bpp alpha masks with per-glyph cell widths.",
        " */",
        f'#include "{header_name}"',
        "",
        "#include <stddef.h>",
        "",
        f"static const uint32_t s_ui_codes[{len(codes)}] = {{",
    ]
    for code in codes:
        label = "degree" if code == 0x00B0 else chr(code)
        lines.append(f"    0x{code:04X}, /* {label} */")
    lines.extend(["};", "", f"static const uint8_t s_ui_widths[{len(widths)}] = {{"])
    for i in range(0, len(widths), 16):
        lines.append("    " + ", ".join(str(w) for w in widths[i : i + 16]) + ",")
    lines.extend(["};", "", f"static const uint16_t s_ui_offsets[{len(offsets)}] = {{"])
    for i in range(0, len(offsets), 12):
        lines.append("    " + ", ".join(str(o) for o in offsets[i : i + 12]) + ",")
    lines.extend(["};", "", f"static const uint8_t s_ui_bitmaps[{cursor}] = {{"])
    for code, bitmap in zip(codes, bitmaps):
        label = "degree" if code == 0x00B0 else chr(code)
        lines.append(f"    /* U+{code:04X} {label} */")
        for i in range(0, len(bitmap), 12):
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 12]) + ",")
    lines.extend(
        [
            "};",
            "",
            f"const uint8_t *{glyph_func}(uint32_t code, uint8_t *width)",
            "{",
            "    for (size_t i = 0; i < sizeof(s_ui_codes) / sizeof(s_ui_codes[0]); ++i) {",
            "        if (s_ui_codes[i] == code) {",
            "            if (width) *width = s_ui_widths[i];",
            "            return s_ui_bitmaps + s_ui_offsets[i];",
            "        }",
            "    }",
            "    if (width) *width = 0;",
            "    return NULL;",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", type=Path, default=Path(__file__).resolve().parents[1] / "main")
    parser.add_argument("--font", type=Path, default=DEFAULT_TITLE_FONT)
    parser.add_argument("--body-font", type=Path, default=DEFAULT_BODY_FONT)
    parser.add_argument("--fallback-font", type=Path, default=DEFAULT_CJK_FALLBACK_FONT)
    parser.add_argument("--body-fallback-font", type=Path, default=DEFAULT_CJK_FALLBACK_FONT)
    parser.add_argument("--magick", default="magick")
    parser.add_argument("--point-size", type=int, default=DEFAULT_TITLE_PT)
    parser.add_argument("--body-point-size", type=int, default=DEFAULT_BODY_PT)
    parser.add_argument("--ui-body-font", type=Path, default=DEFAULT_UI_FONT)
    parser.add_argument("--ui-body-fallback-font", type=Path, default=DEFAULT_CJK_FALLBACK_FONT)
    parser.add_argument("--ui-body-point-size", type=int, default=DEFAULT_UI_BODY_PT)
    parser.add_argument("--width", type=int, default=DEFAULT_TITLE_CELL)
    parser.add_argument("--height", type=int, default=DEFAULT_TITLE_CELL)
    parser.add_argument("--body-width", type=int, default=DEFAULT_BODY_CELL)
    parser.add_argument("--body-height", type=int, default=DEFAULT_BODY_CELL)
    parser.add_argument("--ui-body-height", type=int, default=DEFAULT_UI_BODY_H)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    strings = i18n_catalog.STRINGS
    validate_catalog(strings)
    if not args.font.exists():
        raise FileNotFoundError(args.font)
    if not args.body_font.exists():
        raise FileNotFoundError(args.body_font)
    if not args.ui_body_font.exists():
        raise FileNotFoundError(args.ui_body_font)
    if not args.fallback_font.exists():
        raise FileNotFoundError(args.fallback_font)
    if not args.body_fallback_font.exists():
        raise FileNotFoundError(args.body_fallback_font)
    if not args.ui_body_fallback_font.exists():
        raise FileNotFoundError(args.ui_body_fallback_font)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    emit_i18n_header(args.out_dir / "i18n_catalog.h", strings)
    emit_i18n_source(args.out_dir / "i18n_catalog.c", strings)

    codes = sorted(collect_cjk_codepoints(strings))
    title_fonts = default_font_chain(args.font, args.fallback_font)
    body_fonts = default_font_chain(args.body_font, args.body_fallback_font)
    ui_body_fonts = default_font_chain(args.ui_body_font, args.ui_body_fallback_font)
    bitmaps = [
        pack_readable_4bpp(render_glyph_with_fallback(args.magick, title_fonts,
                                                      args.point_size, args.width,
                                                      args.height, code))
        for code in codes
    ]
    emit_cjk_header(args.out_dir / "text_font_cjk.h",
                    args.width, args.height,
                    "PK_TEXT_CJK", "pk_text_cjk_glyph")
    emit_cjk_source(args.out_dir / "text_font_cjk.c",
                    "text_font_cjk.h", codes, bitmaps,
                    "PK_TEXT_CJK", "pk_text_cjk_glyph")

    body_bitmaps = [
        pack_readable_4bpp(render_glyph_with_fallback(args.magick, body_fonts,
                                                      args.body_point_size,
                                                      args.body_width,
                                                      args.body_height, code))
        for code in codes
    ]
    emit_cjk_header(args.out_dir / "text_font_cjk_body.h",
                    args.body_width, args.body_height,
                    "PK_TEXT_CJK_BODY", "pk_text_cjk_body_glyph")
    emit_cjk_source(args.out_dir / "text_font_cjk_body.c",
                    "text_font_cjk_body.h", codes, body_bitmaps,
                    "PK_TEXT_CJK_BODY", "pk_text_cjk_body_glyph")

    ui_codes = sorted(collect_ui_codepoints(strings))
    ui_widths = [ui_glyph_width(code) for code in ui_codes]
    ui_body_bitmaps = [
        pack_ui_4bpp(render_glyph_with_fallback(args.magick, ui_body_fonts,
                                                args.ui_body_point_size,
                                                width,
                                                args.ui_body_height, code))
        for code, width in zip(ui_codes, ui_widths)
    ]
    emit_ui_font_header(args.out_dir / "text_font_cjk_ui.h",
                        args.ui_body_height, DEFAULT_UI_WIDE_W,
                        "pk_text_cjk_ui_glyph")
    emit_ui_font_source(args.out_dir / "text_font_cjk_ui.c",
                        "text_font_cjk_ui.h", ui_codes, ui_widths,
                        ui_body_bitmaps, "pk_text_cjk_ui_glyph")


if __name__ == "__main__":
    main()
