#!/usr/bin/env python3
"""Generate a fixed-cell 4bpp glyph subset for the PFD font renderer.

The firmware deliberately consumes pre-rasterized glyphs instead of a
runtime TTF engine. That keeps flash/RAM predictable and lets each build
include only the glyphs the UI can actually display.
"""

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path


DEFAULT_CODES = (
    [0x20]
    + list(range(ord("0"), ord("9") + 1))
    + list(range(ord("A"), ord("Z") + 1))
    + [ord(c) for c in "+-./:_()"]
    + [0x7F]
)


def glyph_text(code: int) -> str:
    if code == 0x7F:
        return "°"
    return chr(code)


def c_char_label(code: int) -> str:
    if code == 0x20:
        return "space"
    if code == 0x7F:
        return "degree"
    return chr(code)


def render_glyph(
    magick: str,
    font: Path,
    point_size: int,
    width: int,
    height: int,
    code: int,
    antialias: bool,
) -> bytes:
    if code == 0x20:
        return bytes(width * height)

    with tempfile.TemporaryDirectory() as tmp:
        raw_path = Path(tmp) / "glyph.gray"
        cmd = [
            magick,
            "-background",
            "black",
            "-fill",
            "white",
            "-font",
            str(font),
            "-pointsize",
            str(point_size),
            "-gravity",
            "center",
            "-size",
            f"{width}x{height}",
        ]
        if not antialias:
            cmd.append("+antialias")
        cmd.extend(
            [
                f"label:{glyph_text(code)}",
                "-depth",
                "8",
                f"gray:{raw_path}",
            ]
        )
        subprocess.run(cmd, check=True)
        data = raw_path.read_bytes()

    expected = width * height
    if len(data) != expected:
        raise RuntimeError(f"glyph {code:#x} produced {len(data)} bytes, expected {expected}")
    return data


def pack_4bpp(gray: bytes) -> bytes:
    packed = bytearray()
    for i in range(0, len(gray), 2):
        hi = min(15, (gray[i] + 8) // 17)
        lo = 0
        if i + 1 < len(gray):
            lo = min(15, (gray[i + 1] + 8) // 17)
        packed.append((hi << 4) | lo)
    return bytes(packed)


def emit_header(path: Path, width: int, height: int) -> None:
    path.write_text(
        f"""/* Generated by firmware/scripts/gen_pfd_glyph_font.py. */
#pragma once

#include <stdint.h>

#define PK_FONT_AA_CELL_W {width}
#define PK_FONT_AA_CELL_H {height}
#define PK_FONT_AA_GLYPH_BYTES ((PK_FONT_AA_CELL_W * PK_FONT_AA_CELL_H) / 2)

const uint8_t *pk_font_aa_glyph(unsigned code);
""",
        encoding="utf-8",
    )


def emit_source(
    path: Path,
    header_name: str,
    codes: list[int],
    bitmaps: list[bytes],
    font: Path,
    point_size: int,
    antialias: bool,
) -> None:
    render_label = "4bpp alpha masks" if antialias else "1-bit masks packed into 4bpp cells"
    lines: list[str] = [
        "/* Generated by firmware/scripts/gen_pfd_glyph_font.py.",
        f" * Source font: {font.name}",
        f" * Point size: {point_size}",
        f" * Glyphs are packed as {render_label}, two pixels per byte.",
        " */",
        "",
        f'#include "{header_name}"',
        "",
        "#include <stddef.h>",
        "",
        f"static const uint8_t s_font_aa_codes[{len(codes)}] = {{",
    ]
    for code in codes:
        lines.append(f"    0x{code:02X}, /* {c_char_label(code)} */")
    lines.extend(["};", "", f"static const uint8_t s_font_aa_bitmaps[{len(codes)}][PK_FONT_AA_GLYPH_BYTES] = {{"])

    for code, bitmap in zip(codes, bitmaps):
        lines.append(f"    /* 0x{code:02X} {c_char_label(code)} */")
        lines.append("    {")
        for i in range(0, len(bitmap), 12):
            chunk = ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 12])
            lines.append(f"        {chunk},")
        lines.append("    },")

    lines.extend(
        [
            "};",
            "",
            "const uint8_t *pk_font_aa_glyph(unsigned code)",
            "{",
            "    for (size_t i = 0; i < sizeof(s_font_aa_codes); ++i) {",
            "        if (s_font_aa_codes[i] == code) return s_font_aa_bitmaps[i];",
            "    }",
            "    return NULL;",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--out-c", required=True, type=Path)
    parser.add_argument("--out-h", required=True, type=Path)
    parser.add_argument("--point-size", type=int, default=16)
    parser.add_argument("--width", type=int, default=12)
    parser.add_argument("--height", type=int, default=16)
    parser.add_argument("--chars", default=None)
    parser.add_argument("--magick", default="magick")
    parser.add_argument(
        "--render-mode",
        choices=("aa", "mono"),
        default="aa",
        help="aa keeps grayscale edges; mono disables antialiasing for crisp cockpit readouts",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    codes = DEFAULT_CODES if args.chars is None else sorted({ord(c) for c in args.chars})
    if 0x7F not in codes:
        codes.append(0x7F)
    codes = sorted(set(codes))

    antialias = args.render_mode == "aa"
    bitmaps = [
        pack_4bpp(
            render_glyph(
                args.magick,
                args.font,
                args.point_size,
                args.width,
                args.height,
                code,
                antialias,
            )
        )
        for code in codes
    ]

    emit_header(args.out_h, args.width, args.height)
    emit_source(args.out_c, args.out_h.name, codes, bitmaps, args.font, args.point_size, antialias)


if __name__ == "__main__":
    main()
