#!/usr/bin/env python3
"""
gen_icao_country.py - Build firmware/main/icao_country.c from tar1090 flags.js.

Source:
    https://raw.githubusercontent.com/wiedehopf/tar1090/master/html/flags.js

tar1090's flags.js carries ICAO 24-bit address allocation ranges derived
from ICAO Annex 10 Vol III / Doc 7910. This script parses the JavaScript
object literals and emits the small C lookup table used by the ADS-B LIST
country column.

Usage:
    cd firmware
    scripts/gen_icao_country.py --out main/icao_country.c

For offline or audited updates, download flags.js first and run:
    scripts/gen_icao_country.py --source-file /tmp/flags.js --out main/icao_country.c

Use --check in CI to fail when the checked-in C file is stale.
"""

from __future__ import annotations

import argparse
import re
import sys
import unicodedata
import urllib.request
from pathlib import Path


DEFAULT_URL = "https://raw.githubusercontent.com/wiedehopf/tar1090/master/html/flags.js"
USER_AGENT = (
    "PilotKitBoxIcaoCountryGen/0.1 "
    "(pilotbra@icloud.com; https://github.com/naizhao/Pilot-Kit-Box-ESP32-P4)"
)

RANGE_RE = re.compile(
    r"\{\s*start:\s*0x([0-9A-Fa-f]+),\s*"
    r"end:\s*0x([0-9A-Fa-f]+),\s*"
    r"country:\s*\"([^\"]+)\",\s*"
    r"country_code:\s*\"([A-Za-z]{2})\"\s*\}"
)

ISO2_FIXUPS_BY_COUNTRY = {
    # tar1090 flags.js currently labels the Cook Islands range as "sk",
    # which collides with Slovakia and is not the ISO 3166-1 alpha-2 code.
    "Cook Islands": "CK",
}


def load_source(args: argparse.Namespace) -> str:
    if args.source_file:
        return Path(args.source_file).read_text(encoding="utf-8")
    req = urllib.request.Request(args.source_url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")


def ascii_text(s: str) -> str:
    """Normalize source names to ASCII C string literals."""
    s = s.replace("\u2019", "'").replace("\u2018", "'")
    s = unicodedata.normalize("NFKD", s)
    s = s.encode("ascii", "ignore").decode("ascii")
    return s


def c_string(s: str) -> str:
    return ascii_text(s).replace("\\", "\\\\").replace('"', '\\"')


def parse_ranges(text: str) -> list[tuple[int, int, str, str]]:
    ranges: list[tuple[int, int, str, str]] = []
    for lo_s, hi_s, country, iso2 in RANGE_RE.findall(text):
        lo = int(lo_s, 16)
        hi = int(hi_s, 16)
        if not (0 <= lo <= hi <= 0xFFFFFF):
            raise ValueError(f"invalid ICAO range {lo_s}-{hi_s}")
        country_name = ascii_text(country)
        iso2_norm = ISO2_FIXUPS_BY_COUNTRY.get(country_name, iso2.upper())
        ranges.append((lo, hi, iso2_norm, country_name))
    if not ranges:
        raise RuntimeError("no ICAO ranges found in source")
    ranges.sort(key=lambda r: (r[0], r[1], r[2]))
    return ranges


def emit_c(ranges: list[tuple[int, int, str, str]], source_desc: str) -> str:
    lines: list[str] = []
    lines.append("/*\n")
    lines.append(" * icao_country.c - ICAO 24-bit address -> country lookup table.\n")
    lines.append(" *\n")
    lines.append(" * Generated by firmware/scripts/gen_icao_country.py from:\n")
    lines.append(f" *   {source_desc}\n")
    lines.append(" *\n")
    lines.append(" * The upstream table is derived from ICAO Annex 10 Vol III / Doc 7910\n")
    lines.append(" * address allocations. Keep this file generated; do not hand-edit the\n")
    lines.append(" * range table unless the source data is wrong and the script is updated\n")
    lines.append(" * in the same change.\n")
    lines.append(" */\n")
    lines.append("\n")
    lines.append('#include "icao_country.h"\n')
    lines.append("\n")
    lines.append("#include <stddef.h>\n")
    lines.append("\n")
    lines.append("typedef struct {\n")
    lines.append("    uint32_t       lo;\n")
    lines.append("    uint32_t       hi;\n")
    lines.append("    pk_country_t   c;\n")
    lines.append("} icao_range_t;\n")
    lines.append("\n")
    lines.append("/* Sorted by lo for reviewability. Some small allocations are sub-ranges\n")
    lines.append(" * of larger regional blocks; lookup returns the smallest matching span\n")
    lines.append(" * so territory-specific assignments override parent country blocks. */\n")
    lines.append("static const icao_range_t s_ranges[] = {\n")
    lines.append("    /* lo,        hi,       country */\n")
    for lo, hi, iso2, country in ranges:
        lines.append(
            f'    {{ 0x{lo:06X}, 0x{hi:06X}, {{ "{iso2}", "{c_string(country)}" }} }},\n'
        )
    lines.append("};\n")
    lines.append("#define S_RANGES_N (sizeof(s_ranges) / sizeof(s_ranges[0]))\n")
    lines.append("\n")
    lines.append("const pk_country_t *pk_country_from_icao24(uint32_t icao24)\n")
    lines.append("{\n")
    lines.append("    icao24 &= 0xFFFFFF;\n")
    lines.append("    const icao_range_t *best = NULL;\n")
    lines.append("    uint32_t best_span = 0x01000000u;\n")
    lines.append("    for (size_t i = 0; i < S_RANGES_N; ++i) {\n")
    lines.append("        if (icao24 < s_ranges[i].lo || icao24 > s_ranges[i].hi) {\n")
    lines.append("            continue;\n")
    lines.append("        }\n")
    lines.append("        uint32_t span = s_ranges[i].hi - s_ranges[i].lo;\n")
    lines.append("        if (best == NULL || span < best_span) {\n")
    lines.append("            best = &s_ranges[i];\n")
    lines.append("            best_span = span;\n")
    lines.append("        }\n")
    lines.append("    }\n")
    lines.append("    return best ? &best->c : NULL;\n")
    lines.append("}\n")
    return "".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source-url", default=DEFAULT_URL,
                    help="flags.js URL to fetch when --source-file is absent")
    ap.add_argument("--source-file",
                    help="local flags.js path; avoids network fetch")
    ap.add_argument("--out", default="main/icao_country.c",
                    help="output C source path")
    ap.add_argument("--check", action="store_true",
                    help="fail if --out differs from generated output")
    args = ap.parse_args()

    text = load_source(args)
    ranges = parse_ranges(text)
    source_desc = args.source_file if args.source_file else args.source_url
    generated = emit_c(ranges, source_desc)

    out = Path(args.out)
    if args.check:
        old = out.read_text(encoding="utf-8") if out.exists() else ""
        if old != generated:
            sys.stderr.write(f"{out} is out of date ({len(ranges)} ranges)\n")
            return 1
        sys.stderr.write(f"{out} is up to date ({len(ranges)} ranges)\n")
        return 0

    out.write_text(generated, encoding="utf-8")
    sys.stderr.write(f"wrote {out} ({len(ranges)} ranges)\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
