#!/usr/bin/env python3
"""gen_mag_var.py — 5° 全球磁偏角网格 → firmware/main/mag_var_table.h.

数据源: `geomag` 库内置 WMM 系数（declination，东偏为正，海平面）。
对盒子用途取 5°×5° 网格 + 运行时双线性插值，民航纬度内误差 <1°。
若要换更新的 WMM epoch，替换 geomag 库或其 WMM.COF 后重跑本脚本即可。

用法（从项目根）:  python3 firmware/scripts/gen_mag_var.py
"""
from __future__ import annotations

import sys

try:
    import geomag
except ImportError:
    sys.exit("需要 geomag: python3 -m pip install --user geomag")

STEP = 5
LAT0, LON0 = -90, -180
NLAT = (180 // STEP) + 1      # 37
NLON = (360 // STEP) + 1      # 73

vals: list[int] = []
for i in range(NLAT):
    lat = LAT0 + i * STEP
    for j in range(NLON):
        lon = LON0 + j * STEP
        dec = geomag.declination(lat, lon, 0)   # 度，东偏+
        vals.append(int(round(dec * 100)))      # 0.01° 定点

OUT = "firmware/main/mag_var_table.h"
with open(OUT, "w") as f:
    f.write("#pragma once\n")
    f.write("/* GENERATED by firmware/scripts/gen_mag_var.py — do not edit by hand.\n")
    f.write(" * geomag(WMM) magnetic declination, 东偏为正, 0.01° fixed-point.\n")
    f.write(" * Grid: 5° × 5°, lat[-90,90] × lon[-180,180], bilinear at runtime. */\n")
    f.write(f"#define MAGVAR_STEP {STEP}\n")
    f.write(f"#define MAGVAR_LAT0 {LAT0}\n")
    f.write(f"#define MAGVAR_LON0 {LON0}\n")
    f.write(f"#define MAGVAR_NLAT {NLAT}\n")
    f.write(f"#define MAGVAR_NLON {NLON}\n")
    f.write("static const short MAGVAR_TBL[MAGVAR_NLAT * MAGVAR_NLON] = {\n")
    for k in range(0, len(vals), 12):
        f.write("    " + ",".join(str(v) for v in vals[k:k + 12]) + ",\n")
    f.write("};\n")

print(f"wrote {OUT}: {len(vals)} points ({NLAT}x{NLON})")
# 网格点参考值（lat/lon 均为 5 的倍数）供 host 单测精确比对。
print("--- grid-point reference declinations (for test_mag_var.c) ---")
for lat, lon in [(40, 115), (30, 120), (35, -120), (0, 0), (50, 10), (-35, 150)]:
    print(f"REF {lat:>4},{lon:>5} = {geomag.declination(lat, lon, 0):+.2f}")
