/*
 * airline_codes.c — ICAO 3-letter → IATA + name table.
 *
 * Data sources:
 *   - npow/airline-codes (active=Y rows, github.com/npow/airline-codes),
 *     which itself derives from openflights.org airlines.dat, ICAO Doc
 *     8585 "Designators for Aircraft Operating Agencies", and IATA
 *     airline designators. Provides ~750 carriers.
 *   - Manual additions for modern carriers that post-date the upstream
 *     snapshot — e.g. Jingdong Cargo (JDL/JD), Tianjin Airlines (GCR/GS),
 *     China post-2014 LCCs. See the generator note below if a refresh
 *     is wanted.
 *
 * Sort order: ASCENDING by ICAO code. The lookup uses binary search
 * and assumes this property — keep it stable when adding entries
 * manually, or re-run the regen script.
 *
 * Regen recipe (offline, one-shot):
 *   1. curl raw JSON: github.com/npow/airline-codes/raw/master/airlines.json
 *   2. python: filter active=Y + 3-letter ICAO + 1-3 letter IATA, dedupe
 *      by ICAO, merge with a small manual table of modern carriers, sort
 *      ascending by ICAO, emit one `{ "XXX", "YY", "Name" },` per line.
 *
 * Footprint: ~767 entries × (~12 B pointers + ~25 B strings) ≈ 30 KB
 * in .rodata (flash). Zero DRAM cost. Lookup is < 1 µs with binary
 * search.
 */

#include "airline_codes.h"

#include <ctype.h>
#include <stddef.h>
#include <string.h>

static const pk_airline_t s_airlines[] = {
    { "AAA", "AN", "Ansett Australia" },
    { "AAF", "ZI", "Aigle Azur" },
    { "AAH", "AQ", "Aloha Airlines" },
    { "AAL", "AA", "American Airlines" },
    { "AAN", "WD", "Amsterdam Airlines" },
    { "AAR", "OZ", "Asiana Airlines" },
    { "AAS", "4K", "Askari Aviation" },
    { "AAW", "8U", "Afriqiyah Airways" },
    { "AAY", "G4", "Allegiant Air" },
    { "ABD", "CC", "Air Atlanta Icelandic" },
    { "ABI", "U1", "Aviabus" },
    { "ABL", "BX", "Air Busan" },
    { "ABQ", "ED", "Airblue" },
    { "ABS", "9T", "Transwest Air" },
    { "ABY", "G9", "Air Arabia" },
    { "ACA", "AC", "Air Canada" },
    { "ACI", "SB", "Air Caledonie International" },
    { "ACP", "8V", "Astral Aviation" },
    { "ADE", "ZY", "Ada Air" },
    { "ADH", "AP", "Air One" },
    { "ADO", "HD", "Hokkaido International Airlines" },
    { "ADR", "JP", "Adria Airways" },
    { "AEA", "UX", "Air Europa" },
    { "AEB", "EM", "Aero Benin" },
    { "AEE", "A3", "Aegean Airlines" },
    { "AEL", "PE", "Air Europe" },
    { "AER", "KO", "Alaska Central Express" },
    { "AEU", "5W", "Astraeus" },
    { "AEW", "VV", "Aerosvit Airlines" },
    { "AFG", "FG", "Ariana Afghan Airlines" },
    { "AFL", "SU", "Aeroflot Russian Airlines" },
    { "AFR", "AF", "Air France" },
    { "AGV", "7T", "Air Glaciers" },
    { "AHK", "LD", "AHK Air Hong Kong" },
    { "AHO", "HH", "Air Hamburg (AHO)" },
    { "AHY", "J2", "Azerbaijan Airlines" },
    { "AIA", "U3", "Avies" },
    { "AIC", "AI", "Air India Limited" },
    { "AIQ", "FD", "Thai AirAsia" },
    { "AIZ", "IZ", "Arkia Israel Airlines" },
    { "AJM", "JM", "Air Jamaica" },
    { "AJX", "NQ", "Air Japan" },
    { "AKL", "4A", "Air Kiribati" },
    { "ALK", "UL", "SriLankan Airlines" },
    { "AMC", "KM", "Air Malta" },
    { "AML", "QM", "Air Malawi" },
    { "AMU", "NX", "Air Macau" },
    { "AMX", "AM", "AeroMéxico" },
    { "ANA", "NH", "All Nippon Airways" },
    { "ANE", "YW", "Air Nostrum" },
    { "ANG", "PX", "Air Niugini" },
    { "ANK", "EL", "Air Nippon" },
    { "ANO", "TL", "Airnorth" },
    { "ANT", "4N", "Air North Charter - Canada" },
    { "ANZ", "NZ", "Air New Zealand" },
    { "APW", "JW", "Arrow Air" },
    { "ARD", "2B", "Aerocondor" },
    { "ARE", "4C", "Aires" },
    { "ARF", "GV", "Aero Flight" },
    { "ARG", "AR", "Aerolineas Argentinas" },
    { "ASA", "AS", "Alaska Airlines" },
    { "ASD", "4D", "Air Sinai" },
    { "ASH", "YV", "Mesa Airlines" },
    { "ASQ", "EV", "Atlantic Southeast Airlines" },
    { "ASZ", "OB", "Astrakhan Airlines" },
    { "ATC", "TC", "Air Tanzania" },
    { "ATM", "FO", "Airlines Of Tasmania" },
    { "AUA", "OS", "Austrian Airlines" },
    { "AUB", "IQ", "Augsburg Airways" },
    { "AUH", "MO", "Abu Dhabi Amiri Flight" },
    { "AUI", "PS", "Ukraine International Airlines" },
    { "AUL", "5N", "Aeroflot-Nord" },
    { "AUR", "GR", "Aurigny Air Services" },
    { "AUT", "AU", "Austral Lineas Aereas" },
    { "AVA", "AV", "Avianca - Aerovias Nacionales de Colombia" },
    { "AVN", "NF", "Air Vanuatu" },
    { "AWA", "Y5", "Asia Wings" },
    { "AWE", "HP", "America West Airlines" },
    { "AWI", "ZW", "Air Wisconsin" },
    { "AWM", "AW", "Asian Wings Airways" },
    { "AWQ", "QZ", "Indonesia AirAsia" },
    { "AWU", "7E", "Aeroline GmbH" },
    { "AWW", "6G", "Air Wales" },
    { "AXB", "IX", "Air India Express" },
    { "AXM", "AK", "AirAsia" },
    { "AXZ", "JY", "Aereonautica militare" },
    { "AZA", "AZ", "Alitalia" },
    { "AZN", "Z8", "Amaszonas" },
    { "AZU", "AD", "Azul" },
    { "AZW", "UM", "Air Zimbabwe" },
    { "BAG", "DI", "dba" },
    { "BAW", "BA", "British Airways" },
    { "BBC", "BG", "Biman Bangladesh Airlines" },
    { "BBO", "F7", "Flybaboo" },
    { "BBR", "S3", "Santa Barbara Airlines" },
    { "BCC", "8B", "BusinessAir" },
    { "BCY", "WX", "CityJet" },
    { "BEE", "BE", "Flybe" },
    { "BER", "AB", "Air Berlin" },
    { "BHP", "4T", "Belair Airlines" },
    { "BHS", "UP", "Bahamasair" },
    { "BIE", "DR", "Air Mediterranee" },
    { "BKP", "PG", "Bangkok Airways" },
    { "BLF", "KF", "Blue1" },
    { "BLS", "JV", "Bearskin Lake Air Service" },
    { "BLX", "6B", "TUIfly Nordic" },
    { "BMA", "BD", "bmi" },
    { "BMI", "WW", "bmibaby" },
    { "BMJ", "CH", "Bemidji Airlines" },
    { "BMM", "8A", "Atlas Blue" },
    { "BON", "JA", "Air Bosna" },
    { "BOT", "BP", "Air Botswana" },
    { "BPA", "BV", "Blue Panorama Airlines" },
    { "BQB", "BQ", "Buquebus Líneas Aéreas" },
    { "BRG", "8E", "Bering Air" },
    { "BRQ", "UZ", "El-Buraq Air Transport" },
    { "BRU", "B2", "Belavia Belarusian Airlines" },
    { "BSA", "BZ", "Black Stallion Airways" },
    { "BTA", "XE", "ExpressJet" },
    { "BTI", "BT", "Air Baltic" },
    { "BTN", "B3", "Bhutan Airlines" },
    { "BTV", "7P", "Metro Batavia" },
    { "BUU", "BU", "Baikotovitchestrian Airlines" },
    { "BVT", "J8", "Berjaya Air" },
    { "BWA", "BW", "Caribbean Airlines" },
    { "BWG", "QW", "Blue Wings" },
    { "BZE", "GB", "BRAZIL AIR" },
    { "BZH", "DB", "Brit Air" },
    { "CAL", "CI", "China Airlines" },
    { "CAP", "C2", "CanXplorer" },
    { "CAW", "MN", "Comair" },
    { "CAY", "KX", "Cayman Airways" },
    { "CBG", "GX", "Guangxi Beibu Gulf Airlines" },
    { "CCA", "CA", "Air China" },
    { "CCC", "CB", "CCML Airlines" },
    { "CCM", "XK", "Corse-Mediterranee" },
    { "CDG", "SC", "Shandong Airlines" },
    { "CDP", "Q6", "Aero Condor Peru" },
    { "CEB", "5J", "Cebu Pacific" },
    { "CES", "MU", "China Eastern Airlines" },
    { "CFE", "CJ", "BA CityFlyer" },
    { "CFG", "DE", "Condor Flugdienst" },
    { "CGP", "8L", "Cargo Plus Aviation" },
    { "CHB", "GX", "Beibu Gulf Airlines" },
    { "CHH", "HU", "Hainan Airlines" },
    { "CHP", "6A", "Consorcio Aviaxsa" },
    { "CHQ", "RP", "Chautauqua Airlines" },
    { "CIF", "1F", "CB Airways UK ( Interliging Flights )" },
    { "CIM", "QI", "Cimber Air" },
    { "CJC", "9L", "Colgan Air" },
    { "CKK", "CK", "China Cargo Airlines" },
    { "CLH", "CL", "Lufthansa CityLine" },
    { "CLI", "XG", "Calima Aviacion" },
    { "CLW", "C0", "Centralwings" },
    { "CMI", "CS", "Continental Micronesia" },
    { "CMP", "CM", "Copa Airlines" },
    { "COM", "OH", "Comair" },
    { "CPA", "CX", "Cathay Pacific" },
    { "CPN", "RV", "Caspian Airlines" },
    { "CQH", "9S", "Spring Airlines" },
    { "CQN", "OQ", "Chongqing Airlines" },
    { "CRK", "HX", "Hong Kong Airlines" },
    { "CRL", "SS", "Corsairfly" },
    { "CSA", "OK", "Czech Airlines" },
    { "CSC", "3U", "Sichuan Airlines" },
    { "CSH", "FM", "Shanghai Airlines" },
    { "CSN", "CZ", "China Southern Airlines" },
    { "CSS", "O3", "SF Airlines" },
    { "CSZ", "ZH", "Shenzhen Airlines" },
    { "CTN", "OU", "Croatia Airlines" },
    { "CUA", "HR", "China United Airlines" },
    { "CUB", "CU", "Cubana de Aviación" },
    { "CUH", "UQ", "Urumqi Air" },
    { "CVA", "CV", "Air Chathams" },
    { "CWK", "KR", "Comores Airlines" },
    { "CWM", "CW", "Air Marshall Islands" },
    { "CXA", "MF", "Xiamen Airlines" },
    { "CYH", "3Q", "Yunnan Airlines" },
    { "CYP", "CY", "Cyprus Airways" },
    { "CYZ", "8Y", "China Postal Airlines" },
    { "DAH", "AH", "Air Algerie" },
    { "DAL", "DL", "Delta Air Lines" },
    { "DAO", "D3", "Daallo Airlines" },
    { "DAT", "SN", "Brussels Airlines" },
    { "DHI", "KI", "Adam Air" },
    { "DJB", "D8", "Djibouti Airlines" },
    { "DKH", "HO", "Juneyao Airlines" },
    { "DLA", "EN", "Air Dolomiti" },
    { "DLH", "LH", "Lufthansa" },
    { "DMO", "E3", "Domodedovo Airlines" },
    { "DNV", "D9", "Aeroflot-Don" },
    { "DOA", "DO", "Dominicana de Aviaci" },
    { "DOB", "QD", "Dobrolet" },
    { "DRD", "NM", "Air Madrid" },
    { "DRK", "KB", "Druk Air" },
    { "DRU", "6R", "Alrosa Mirny Air Enterprise" },
    { "DSM", "4M", "LAN Argentina" },
    { "DSY", "DH", "Dennis Sky" },
    { "DTA", "DT", "TAAG Angola Airlines" },
    { "DTR", "DX", "DAT Danish Air Transport" },
    { "DWT", "0D", "Darwin Airline" },
    { "EAL", "EA", "European Air Express" },
    { "EAV", "13", "Eastern Atlantic Virtual Airlines" },
    { "ECA", "UI", "Eurocypria Airlines" },
    { "EDW", "WK", "Edelweiss Air" },
    { "EEA", "EU", "Empresa Ecuatoriana De Aviacion" },
    { "EEU", "GJ", "Eurofly Service" },
    { "EFA", "EF", "Far Eastern Air Transport" },
    { "EGF", "MQ", "American Eagle Airlines" },
    { "EIA", "EZ", "Evergreen International Airlines" },
    { "EIN", "EI", "Aer Lingus" },
    { "EJA", "1I", "NetJets" },
    { "ELA", "DK", "Eastland Air" },
    { "ELK", "--", "ELK Airways" },
    { "ELL", "OV", "Estonian Air" },
    { "ELO", "K2", "Eurolot" },
    { "ELY", "LY", "El Al Israel Airlines" },
    { "EPA", "DZ", "Donghai Airlines" },
    { "ERO", "7L", "Sun D'Or" },
    { "ERR", "7H", "Era Alaska" },
    { "ERT", "B8", "Eritrean Airlines" },
    { "ESK", "NE", "SkyEurope" },
    { "ESR", "ZE", "Eastar Jet" },
    { "ETD", "EY", "Etihad Airways" },
    { "ETH", "ET", "Ethiopian Airlines" },
    { "EUV", "ES", "EuropeSky" },
    { "EVA", "BR", "EVA Air" },
    { "EWG", "EW", "Eurowings" },
    { "EXS", "LS", "Jet2.com" },
    { "EZE", "T3", "Eastern Airways" },
    { "EZY", "U2", "easyJet" },
    { "FAB", "7F", "First Air" },
    { "FBL", "F1", "Fly Brasil" },
    { "FCA", "DP", "First Choice Airways" },
    { "FDB", "FZ", "Fly Dubai" },
    { "FFM", "FY", "Firefly" },
    { "FFT", "F9", "Frontier Airlines" },
    { "FFV", "5H", "Fly540" },
    { "FHE", "HW", "Hello" },
    { "FHI", "FH", "FlyHigh Airlines Ireland (FH)" },
    { "FIF", "OF", "Air Finland" },
    { "FIN", "AY", "Finnair" },
    { "FJI", "FJ", "Air Pacific" },
    { "FLG", "9E", "Pinnacle Airlines" },
    { "FLI", "RC", "Atlantic Airways" },
    { "FLT", "B5", "Flightline" },
    { "FLZ", "QH", "Air Florida" },
    { "FPT", "PO", "FlyPortugal" },
    { "FRE", "FP", "Freedom Air" },
    { "FTA", "2F", "Frontier Flying Service" },
    { "FWI", "TX", "Air Caraïbes" },
    { "FWL", "RF", "Florida West International Airways" },
    { "FXI", "NY", "Air Iceland" },
    { "FXX", "FU", "Felix Airways" },
    { "GAI", "3R", "Moskovia Airlines" },
    { "GAO", "DC", "Golden Air" },
    { "GAP", "2P", "Air Philippines" },
    { "GBA", "GF", "Gulf Air Bahrain" },
    { "GBK", "GY", "Gabon Airlines" },
    { "GBL", "GT", "GB Airways" },
    { "GCR", "GS", "Tianjin Airlines" },
    { "GDR", "GP", "Gadair European Airlines" },
    { "GEC", "LH", "Lufthansa Cargo" },
    { "GER", "GM", "German International Air Lines" },
    { "GFG", "QB", "Georgian National Airlines" },
    { "GFY", "XX", "Greenfly" },
    { "GHB", "G0", "Ghana International Airlines" },
    { "GIA", "GA", "Garuda Indonesia" },
    { "GIE", "E4", "Elysian Airlines" },
    { "GIP", "2U", "Air Guinee Express" },
    { "GJS", "G7", "GoJet Airlines" },
    { "GLA", "ZK", "Great Lakes Airlines" },
    { "GLG", "2K", "Aerolineas Galapagos (Aerogal)" },
    { "GLO", "G3", "Gol Transportes Aéreos" },
    { "GLP", "GH", "Globus" },
    { "GMI", "ST", "Germania" },
    { "GOW", "G8", "Go Air" },
    { "GRL", "GL", "Air Greenland" },
    { "GSM", "B4", "Flyglobespan" },
    { "GTI", "5Y", "Atlas Air" },
    { "GUY", "GG", "Air Guyane" },
    { "GWI", "4U", "Germanwings" },
    { "GWL", "B7", "Uni Air" },
    { "GWY", "U5", "USA3000 Airlines" },
    { "GZP", "4G", "Gazpromavia" },
    { "HAG", "H6", "Hageland Aviation Services" },
    { "HAL", "HA", "Hawaiian Airlines" },
    { "HAM", "2T", "Haiti Ambassador Airlines" },
    { "HCW", "V9", "Star1 Airlines" },
    { "HDA", "KA", "Dragonair" },
    { "HEJ", "T4", "Hellas Jet" },
    { "HER", "UD", "Hex'Air" },
    { "HFR", "8H", "Heli France" },
    { "HHI", "4R", "Hamburg International" },
    { "HKC", "RH", "Hongkong Air Cargo" },
    { "HKE", "UO", "Hong Kong Express Airways" },
    { "HLF", "HF", "Hapagfly" },
    { "HLX", "X3", "TUIfly" },
    { "HNX", "HN", "Hankook Airline" },
    { "HVN", "VN", "Vietnam Airlines" },
    { "HYM", "HC", "Himalayan Airlines" },
    { "HZA", "BN", "Horizon Airlines" },
    { "IAA", "IO", "Indonesian Airlines" },
    { "IAC", "IC", "Indian Airlines" },
    { "IAW", "IA", "Iraqi Airways" },
    { "IBB", "NT", "Binter Canarias" },
    { "IBE", "IB", "Iberia Airlines" },
    { "IBS", "I2", "Iberia Express" },
    { "IBX", "FW", "Ibex Airlines" },
    { "ICE", "FI", "Icelandair" },
    { "ICL", "5C", "CAL Cargo Air Lines" },
    { "IDS", "I5", "Indonesia Sky" },
    { "IDX", "XT", "Indonesia AirAsia X" },
    { "IGO", "6E", "IndiGo Airlines" },
    { "IKA", "GI", "Itek Air" },
    { "ILN", "D6", "Interair South Africa" },
    { "IMP", "HT", "Hellenic Imperial Airways" },
    { "IPV", "PA", "Parmiss Airlines (IPV)" },
    { "IRA", "IR", "Iran Air" },
    { "IRB", "B9", "Iran Airtour" },
    { "IRC", "EP", "Iran Aseman Airlines" },
    { "IRK", "Y9", "Kish Air" },
    { "IRM", "W5", "Mahan Air" },
    { "ISK", "3L", "Intersky" },
    { "ISR", "6H", "Israir" },
    { "ISS", "IG", "Meridiana" },
    { "ISV", "WC", "Islena De Inversiones" },
    { "ISW", "IF", "Islas Airways" },
    { "ISX", "IP", "Island Spirit" },
    { "ITK", "ID", "Interlink Airlines" },
    { "ITX", "IK", "Imair Airlines" },
    { "IWA", "ZM", "Apache Air" },
    { "IWD", "TY", "Iberworld" },
    { "IYE", "IY", "Yemenia" },
    { "JAA", "EG", "Japan Asia Airways" },
    { "JAB", "W9", "Air Bagan" },
    { "JAE", "JD", "Beijing Capital Airlines" },
    { "JAF", "JF", "Jetairfly" },
    { "JAI", "9W", "Jet Airways" },
    { "JAL", "JL", "Japan Airlines" },
    { "JAS", "JD", "Japan Air System" },
    { "JAT", "JU", "Jat Airways" },
    { "JAZ", "JO", "JALways" },
    { "JBA", "JB", "Helijet" },
    { "JBU", "B6", "JetBlue Airways" },
    { "JDL", "JD", "Jingdong Cargo Airlines" },
    { "JET", "IV", "Wind Jet" },
    { "JEX", "JC", "JAL Express" },
    { "JFU", "8J", "Jet4You" },
    { "JJA", "7C", "Jeju Air" },
    { "JKK", "JK", "Spanair" },
    { "JNA", "LJ", "Jin Air" },
    { "JOR", "0B", "Blue Air" },
    { "JOY", "JR", "Joy Air" },
    { "JSA", "3K", "Jetstar Asia Airways" },
    { "JSR", "JX", "Jusur airways" },
    { "JST", "JQ", "Jetstar Airways" },
    { "JTA", "NU", "Japan Transocean Air" },
    { "JTO", "NR", "Jettor Airlines" },
    { "JZA", "QK", "Air Canada Jazz" },
    { "JZR", "J9", "Jazeera Airways" },
    { "KAC", "KU", "Kuwait Airways" },
    { "KAL", "KE", "Korean Air" },
    { "KAP", "9K", "Cape Air" },
    { "KBR", "K7", "KoralBlue Airlines" },
    { "KEN", "M5", "Kenmore Air" },
    { "KFR", "IT", "Kingfisher Airlines" },
    { "KGL", "7K", "Kogalymavia Air Company" },
    { "KGO", "ZC", "Korongo Airlines" },
    { "KHB", "H8", "Dalavia" },
    { "KHK", "KH", "Kharkiv Airlines" },
    { "KIL", "GW", "Kuban Airlines" },
    { "KJC", "7B", "Krasnojarsky Airlines" },
    { "KKK", "KK", "Atlasjet" },
    { "KLC", "WA", "KLM Cityhopper" },
    { "KLM", "KL", "KLM Royal Dutch Airlines" },
    { "KMF", "RQ", "Kam Air" },
    { "KNE", "XY", "Nas Air" },
    { "KNI", "KD", "KD Avia" },
    { "KOL", "CQ", "SOCHI AIR" },
    { "KOQ", "K1", "Kostromskie avialinii" },
    { "KOR", "JS", "Air Koryo" },
    { "KQA", "KQ", "Kenya Airways" },
    { "KRP", "V3", "Carpatair" },
    { "KSY", "KY", "KSY" },
    { "KZK", "9Y", "Air Kazakhstan" },
    { "KZR", "KC", "Air Astana" },
    { "KZU", "GO", "Kuzu Airlines Cargo" },
    { "LAA", "LN", "Libyan Arab Airlines" },
    { "LAJ", "KJ", "British Mediterranean Airways" },
    { "LAM", "LM", "Linhas A" },
    { "LAN", "LA", "LAN Airlines" },
    { "LAO", "QV", "Lao Airlines" },
    { "LAP", "PZ", "TAM Mercosur" },
    { "LBC", "LV", "Albanian Airlines" },
    { "LBL", "L8", "Line Blue" },
    { "LBT", "BJ", "Nouvel Air Tunisie" },
    { "LDA", "NG", "Lauda Air" },
    { "LGL", "LG", "Luxair" },
    { "LGW", "HE", "Luftfahrtgesellschaft Walter" },
    { "LHN", "EO", "Express One International" },
    { "LIA", "LI", "Leeward Islands Air Transport" },
    { "LIL", "TE", "FlyLal" },
    { "LIX", "C4", "LionXpress" },
    { "LJJ", "L4", "Luchsh Airlines" },
    { "LLM", "YL", "Yamal Airlines" },
    { "LMM", "LQ", "LCM AIRLINES" },
    { "LMU", "UJ", "AlMasria Universal Airlines" },
    { "LNE", "XL", "Aerolane" },
    { "LNI", "JT", "Lion Mentari Airlines" },
    { "LOC", "ZQ", "Locair" },
    { "LOF", "AX", "Trans States Airlines" },
    { "LOO", "PQ", "LSM Airlines" },
    { "LOT", "LO", "LOT Polish Airlines" },
    { "LPE", "LP", "LAN Peru" },
    { "LPR", "MJ", "L" },
    { "LRC", "LR", "LACSA" },
    { "LTE", "XO", "LTE International Airways" },
    { "LTO", "L3", "LTU Austria" },
    { "LTR", "L5", "Lufttransport" },
    { "LTU", "LT", "LTU International" },
    { "LUR", "TD", "Atlantis European Airways" },
    { "LXP", "LU", "LAN Express" },
    { "LXR", "LK", "Air Luxor" },
    { "LZB", "FB", "Bulgaria Air" },
    { "MAA", "M7", "MasAir" },
    { "MAC", "R5", "Malta Air Charter" },
    { "MAH", "MA", "Malév" },
    { "MAI", "L6", "Mauritania Airlines International" },
    { "MAK", "IN", "MAT Macedonian Airlines" },
    { "MAS", "MH", "Malaysia Airlines" },
    { "MAU", "MK", "Air Mauritius" },
    { "MAV", "ML", "Maldivo Airlines" },
    { "MDA", "AE", "Mandarin Airlines" },
    { "MDG", "MD", "Air Madagascar" },
    { "MDL", "RI", "Mandala Airlines" },
    { "MDO", "D1", "Domenican Airlines" },
    { "MDV", "2M", "Moldavian Airlines" },
    { "MDW", "JI", "Midway Airlines" },
    { "MEA", "ME", "Middle East Airlines" },
    { "MEP", "YX", "Midwest Airlines" },
    { "MES", "XJ", "Mesaba Airlines" },
    { "MGL", "OM", "MIAT Mongolian Airlines" },
    { "MGX", "YM", "Montenegro Airlines" },
    { "MJG", "DF", "Michael Airlines" },
    { "MJX", "4L", "Euroline" },
    { "MKD", "6F", "MAT Airways" },
    { "MKG", "P8", "Air Mekong" },
    { "MKU", "WP", "Island Air (WP)" },
    { "MLA", "Q5", "40-Mile Air" },
    { "MLD", "9U", "Air Moldova" },
    { "MMA", "8M", "Myanmar Airways International" },
    { "MMD", "6I", "Alsie Express" },
    { "MNA", "MZ", "Merpati Nusantara Airlines" },
    { "MNB", "MB", "MNG Airlines" },
    { "MNO", "JE", "Mango" },
    { "MNP", "SM", "Spirit of Manila Airlines" },
    { "MOV", "NN", "VIM Airlines" },
    { "MPD", "A7", "Air Plus Comet" },
    { "MPE", "5T", "Canadian North" },
    { "MPH", "MP", "Martinair" },
    { "MRS", "Y8", "Marusya Airways" },
    { "MSI", "M9", "Motor Sich" },
    { "MSR", "MS", "Egyptair" },
    { "MVD", "KV", "Kavminvodyavia" },
    { "MWA", "MY", "Midwest Airlines (Egypt)" },
    { "MXA", "MX", "Mexicana de Aviaci" },
    { "MXD", "OD", "Malindo Air" },
    { "MXI", "I6", "MexicanaLink" },
    { "MYD", "MW", "Maya Island Air" },
    { "MYT", "VZ", "MyTravel Airways" },
    { "MYU", "2Y", "My Indo Airlines" },
    { "NAK", "Q9", "Arik Niger" },
    { "NAS", "UE", "Nasair" },
    { "NAX", "DY", "Norwegian Air Shuttle" },
    { "NCR", "N8", "National Air Cargo" },
    { "NDC", "LF", "FlyNordic" },
    { "NEA", "EJ", "New England Airlines" },
    { "NGB", "NJ", "Nordic Global Airlines" },
    { "NIA", "NP", "Nile Air" },
    { "NIG", "AJ", "Aero Contractors" },
    { "NJE", "1I", "NetJets Europe" },
    { "NJS", "NC", "National Jet Systems" },
    { "NKF", "8N", "Barents AirLink" },
    { "NKS", "NK", "Spirit Airlines" },
    { "NLY", "HG", "Niki" },
    { "NMB", "SW", "Air Namibia" },
    { "NMI", "LW", "Pacific Wings" },
    { "NOK", "DD", "Nok Air" },
    { "NSE", "9R", "SATENA" },
    { "NTJ", "2N", "NextJet" },
    { "NTW", "CE", "Nationwide Airlines" },
    { "NWA", "NW", "Northwest Airlines" },
    { "NXB", "XB", "NEXT Brasil" },
    { "OAB", "O1", "Orbit Airlines Azerbaijan" },
    { "OAE", "OY", "Omni Air International" },
    { "OAL", "OA", "Olympic Airlines" },
    { "OAW", "2L", "Helvetic Airways" },
    { "OCA", "R7", "Aserca Airlines" },
    { "OEA", "OX", "Orient Thai Airlines" },
    { "OGN", "QO", "Origin Pacific Airways" },
    { "OHK", "O8", "Oasis Hong Kong Airlines" },
    { "OKA", "BK", "Okay Airways" },
    { "OLA", "OJ", "Overland Airways" },
    { "OLT", "OL", "Ostfriesische Lufttransport" },
    { "OMA", "WY", "Oman Air" },
    { "OME", "MR", "Homer Air" },
    { "ONE", "O6", "Oceanair" },
    { "OOM", "Z4", "Zoom Airlines" },
    { "ORB", "R2", "Orenburg Airlines" },
    { "ORC", "OI", "Orchid Airlines" },
    { "OZJ", "O7", "Ozjet Airlines" },
    { "PAL", "PR", "Philippine Airlines" },
    { "PAO", "PH", "Polynesian Airlines" },
    { "PBA", "9Q", "PB Air" },
    { "PCO", "8P", "Pacific Coastal Airline" },
    { "PDC", "BK", "Potomac Air" },
    { "PDT", "PI", "Piedmont Airlines (1948-1989)" },
    { "PEC", "Q8", "Pacific East Asia Cargo Airlines" },
    { "PEL", "OT", "Aeropelican Air Services" },
    { "PEN", "KS", "Peninsula Airways" },
    { "PGA", "NI", "Portugalia" },
    { "PGT", "PC", "Pegasus Airlines" },
    { "PIA", "PK", "Pakistan International Airlines" },
    { "PIC", "BL", "Jetstar Pacific" },
    { "PLI", "PL", "Aeroper" },
    { "PLR", "J3", "Northwestern Air" },
    { "PMT", "U4", "PMTair" },
    { "PMW", "I7", "Paramount Airways" },
    { "PNR", "PV", "PAN Air" },
    { "POE", "PD", "Porter Airlines" },
    { "PQW", "WQ", "PanAm World Airways" },
    { "PRF", "PW", "Precision Air" },
    { "PUA", "PU", "PLUNA" },
    { "QDA", "AQ", "9 Air" },
    { "QER", "Q3", "SOCHI AIR CHATER" },
    { "QFA", "QF", "Qantas" },
    { "QQE", "QE", "Qatar Executive" },
    { "QTR", "QR", "Qatar Airways" },
    { "QXE", "QX", "Horizon Air" },
    { "RAB", "RN", "Rainbow Air (RAI)" },
    { "RAC", "VJ", "Royal Air Cambodge" },
    { "RAE", "YS", "Régional" },
    { "RAM", "AT", "Royal Air Maroc" },
    { "RAR", "GZ", "Air Rarotonga" },
    { "RAW", "KG", "Royal Airways" },
    { "RAY", "RY", "Rainbow Air Canada" },
    { "RBA", "BI", "Royal Brunei Airlines" },
    { "RBG", "E5", "Air Arabia Egypt" },
    { "RBY", "V2", "Vision Airlines (V2)" },
    { "REA", "RE", "Aer Arann" },
    { "REP", "P7", "Regional Paraguaya" },
    { "REU", "UU", "Air Austral" },
    { "RFJ", "RL", "Royal Falcon" },
    { "RIT", "6K", "Asian Spirit" },
    { "RJA", "RJ", "Royal Jordanian" },
    { "RKA", "RK", "Air Afrique" },
    { "RLA", "A5", "Airlinair" },
    { "RLN", "QL", "Aero Lanka" },
    { "RNA", "RA", "Nepal Airlines" },
    { "RNE", "20", "Air Salone" },
    { "RNV", "U8", "Armavia" },
    { "RNX", "1T", "1Time Airline" },
    { "RNY", "RM", "Rainbow Air US" },
    { "RON", "ON", "Nauru Air Corporation" },
    { "ROT", "RO", "Tarom" },
    { "RPA", "RW", "Republic Airlines" },
    { "RPB", "P5", "AeroRep" },
    { "RRJ", "R8", "AirRussia" },
    { "RSH", "S2", "Air Sahara" },
    { "RSR", "BF", "Aero-Service" },
    { "RSU", "5L", "Aerosur" },
    { "RSY", "H5", "I-Fly" },
    { "RUE", "RU", "Rainbow Air Euro" },
    { "RUS", "C9", "Cirrus Airlines" },
    { "RWD", "WB", "Rwandair Express" },
    { "RWW", "ER", "Fly Europa" },
    { "RWZ", "WZ", "Red Wings" },
    { "RXA", "ZL", "Regional Express" },
    { "RYN", "RD", "Ryan International Airlines" },
    { "RYR", "FR", "Ryanair" },
    { "RZO", "S4", "SATA International" },
    { "SAA", "SA", "South African Airways" },
    { "SAI", "NL", "Shaheen Air International" },
    { "SAL", "S0", "Spike Airlines" },
    { "SAR", "0G", "Sprintair" },
    { "SAS", "SK", "Scandinavian Airlines System" },
    { "SAT", "SP", "SATA Air Acores" },
    { "SBD", "S8", "Snowbird Airlines" },
    { "SBI", "S7", "S7 Airlines" },
    { "SBS", "BB", "Seaborne Airlines" },
    { "SCO", "TR", "Scoot" },
    { "SCX", "SY", "Sun Country Airlines" },
    { "SDM", "FV", "Rossiya-Russian Airlines" },
    { "SDR", "CF", "City Airline" },
    { "SEH", "GQ", "Sky Express" },
    { "SEJ", "SG", "Spicejet" },
    { "SEU", "SE", "XL Airways France" },
    { "SEY", "HM", "Air Seychelles" },
    { "SFJ", "7G", "Star Flyer" },
    { "SGG", "DN", "Senegal Airlines" },
    { "SGY", "N5", "Skagway Air Service" },
    { "SHA", "SH", "Sharp Airlines" },
    { "SIA", "SQ", "Singapore Airlines" },
    { "SIB", "5M", "Sibaviatrans" },
    { "SIH", "SI", "Skynet Airlines" },
    { "SJS", "76", "Southjet" },
    { "SJY", "SJ", "Sriwijaya Air" },
    { "SKU", "H2", "Sky Airline" },
    { "SKW", "OO", "SkyWest" },
    { "SKX", "JZ", "Skyways Express" },
    { "SKY", "BC", "Skymark Airlines" },
    { "SLC", "SO", "Salsa d\\'Haiti" },
    { "SLI", "5D", "Aerolitoral" },
    { "SLK", "MI", "SilkAir" },
    { "SLM", "PY", "Surinam Airways" },
    { "SMJ", "Z3", "Avient Aviation" },
    { "SMX", "XM", "Alitalia Express" },
    { "SMY", "ZS", "Sama Airlines" },
    { "SNB", "NB", "Sterling Airlines" },
    { "SNC", "2Q", "Air Cargo Carriers" },
    { "SNJ", "6J", "Skynet Asia Airways" },
    { "SOL", "IE", "Solomon Airlines" },
    { "SOV", "6W", "Saratov Aviation Division" },
    { "SOZ", "HZ", "Sat Airlines" },
    { "SPM", "PJ", "Air Saint Pierre" },
    { "SQC", "SQ", "Singapore Airlines Cargo" },
    { "SQH", "K5", "SeaPort Airlines" },
    { "SRH", "FT", "Siem Reap Airways" },
    { "SRQ", "DG", "South East Asian Airlines" },
    { "SSV", "5G", "Skyservice Airlines" },
    { "STP", "8F", "STP Airways" },
    { "STU", "FS", "Servicios de Transportes A" },
    { "SUD", "SD", "Sudan Airways" },
    { "SVA", "SV", "Saudi Arabian Airlines" },
    { "SVR", "U6", "Ural Airlines" },
    { "SWA", "WN", "Southwest Airlines" },
    { "SWD", "A4", "Southern Winds Airlines" },
    { "SWR", "LX", "Swiss International Air Lines" },
    { "SWV", "WV", "Swe Fly" },
    { "SXR", "XW", "Sky Express" },
    { "SXS", "XQ", "SunExpress" },
    { "SYL", "R3", "Aircompany Yakutia" },
    { "SYR", "RB", "Syrian Arab Airlines" },
    { "SYX", "AL", "Skywalk Airlines" },
    { "TAE", "EQ", "TAME" },
    { "TAK", "U9", "Tatarstan Airlines" },
    { "TAM", "JJ", "TAM Brazilian Airlines" },
    { "TAO", "VW", "Aeromar" },
    { "TAP", "TP", "TAP Portugal" },
    { "TAR", "TU", "Tunisair" },
    { "TAT", "TA", "Grupo TACA" },
    { "TBA", "TV", "Tibet Airlines" },
    { "TBZ", "TB", "TrasBrasil" },
    { "TCF", "S5", "Shuttle America" },
    { "TCG", "T2", "Thai Air Cargo" },
    { "TCV", "VR", "TACV" },
    { "TCW", "FQ", "Thomas Cook Airlines" },
    { "TCX", "MT", "Thomas Cook Airlines" },
    { "TFL", "OR", "Arkefly" },
    { "TGG", "TT", "Tigerair Australia" },
    { "TGZ", "A9", "Georgian Airways" },
    { "THA", "TG", "Thai Airways International" },
    { "THI", "TI", "TransHolding" },
    { "THS", "TH", "TransBrasil Airlines" },
    { "THT", "TN", "Air Tahiti Nui" },
    { "THY", "TK", "Turkish Airlines" },
    { "TIB", "8R", "TRIP Linhas A" },
    { "TJA", "TJ", "T.J. Air" },
    { "TJT", "T7", "Twin Jet" },
    { "TLM", "SL", "Thai Lion Air" },
    { "TNA", "GE", "TransAsia Airways" },
    { "TNM", "3P", "Tiara Air" },
    { "TOK", "CG", "Airlines PNG" },
    { "TOM", "BY", "Thomsonfly" },
    { "TOS", "PM", "Tropic Air" },
    { "TPA", "QT", "TAMPA" },
    { "TRA", "HV", "Transavia Holland" },
    { "TRS", "FL", "AirTran Airways" },
    { "TSC", "TS", "Air Transat" },
    { "TSO", "UN", "Transaero Airlines" },
    { "TUA", "T5", "Turkmenistan Airlines" },
    { "TUI", "UG", "Tuninter" },
    { "TUS", "M3", "ABSA - Aerolinhas Brasileiras" },
    { "TVF", "TO", "Transavia France" },
    { "TVS", "QS", "Travel Service" },
    { "TWB", "TW", "Tway Airlines" },
    { "TWN", "EC", "Avialeasing Aviation Company" },
    { "TXW", "TQ", "Texas Wings" },
    { "TYR", "VO", "Tyrolean Airways" },
    { "TYS", "YO", "TransHolding System" },
    { "UAE", "EK", "Emirates" },
    { "UAL", "UA", "United Airlines" },
    { "UBA", "UB", "Myanma Airways" },
    { "UBD", "4H", "United Airways" },
    { "UBG", "BS", "US-Bangla Airlines" },
    { "UCA", "C5", "CommutAir" },
    { "UEA", "EU", "Chengdu Airlines" },
    { "UGX", "QU", "East African" },
    { "UIA", "B7", "Uni Air" },
    { "UKM", "UF", "UM Airlines" },
    { "UPA", "GS", "Air Foyle" },
    { "URC", "UQ", "Urumqi Airlines" },
    { "URN", "3T", "Turan Air" },
    { "USA", "US", "US Airways" },
    { "UTA", "UT", "UTair Aviation" },
    { "UTY", "QQ", "Alliance Airlines" },
    { "UWW", "II", "LSM International" },
    { "UZB", "HY", "Uzbekistan Airways" },
    { "VAS", "V8", "ATRAN Cargo Airlines" },
    { "VBW", "2J", "Air Burkina" },
    { "VCV", "V0", "Conviasa" },
    { "VDA", "VI", "Volga-Dnepr Airlines" },
    { "VEX", "TV", "Virgin Express" },
    { "VGN", "VK", "Virgin Nigeria Airways" },
    { "VIM", "VL", "Air VIA" },
    { "VIR", "VS", "Virgin Atlantic Airways" },
    { "VKH", "VQ", "Viking Hellas" },
    { "VKJ", "KT", "VickJet" },
    { "VLE", "VE", "Volare Airlines" },
    { "VLG", "VY", "Vueling Airlines" },
    { "VLK", "XF", "Vladivostok Air" },
    { "VLM", "VG", "VLM Airlines" },
    { "VLO", "LC", "Varig Log" },
    { "VLU", "VF", "Valuair" },
    { "VNP", "VH", "Virgin Pacific" },
    { "VOI", "Y4", "Volaris" },
    { "VOZ", "VA", "Virgin Australia" },
    { "VRD", "VX", "Virgin America" },
    { "VRN", "RG", "VRG Linhas Aereas" },
    { "VSP", "VP", "VASP" },
    { "VSV", "DV", "Scat Air" },
    { "VTA", "VT", "Air Tahiti" },
    { "VTI", "UK", "Vistara" },
    { "VUN", "VU", "Air Ivoire" },
    { "VVC", "5Z", "VivaColombia" },
    { "VVM", "ZG", "Viva Macau" },
    { "VVN", "47", "88" },
    { "VWA", "YY", "Virginwings" },
    { "WAU", "WU", "Wizz Air Ukraine" },
    { "WBA", "FC", "Finncomm Airlines" },
    { "WEB", "WJ", "WebJet Linhas A" },
    { "WER", "W4", "AeroWorld" },
    { "WIF", "WF", "Widerøe" },
    { "WJA", "WS", "WestJet" },
    { "WLC", "2W", "Welcome Air" },
    { "WOA", "WO", "World Airways" },
    { "WON", "IW", "Wings Air" },
    { "WTA", "FK", "Africa West" },
    { "WVL", "8Z", "Wizz Air Hungary" },
    { "WZZ", "W6", "Wizz Air" },
    { "XAN", "78", "Southjet cargo" },
    { "XAU", "XA", "XAIR USA" },
    { "XAX", "D7", "AirAsia X" },
    { "XLA", "JN", "Excel Airways" },
    { "XPT", "XP", "XPTO" },
    { "YCC", "YC", "Ciel Canadien" },
    { "YCP", "CN", "Canadian National Airways" },
    { "YEL", "YE", "Yellowtail" },
    { "YZR", "Y8", "Suparna Airlines" },
    { "YZZ", "YZ", "LSM AIRLINES" },
    { "ZCS", "77", "Southjet connect" },
    { "ZNA", "ZN", "Zenith International Airline" },
    { "ZTF", "7M", "Mongolian International Air Lines" },
    { "ZTT", "Z6", "ZABAIKAL AIRLINES" },
    { "ZXY", "ZX", "Japan Regio" },
    { "ZZZ", "ZP", "Zabaykalskii Airlines" },
};
#define S_AIRLINES_N (sizeof(s_airlines) / sizeof(s_airlines[0]))

const pk_airline_t *pk_airline_from_icao3(const char *icao3)
{
    if (icao3 == NULL) return NULL;
    if (icao3[0] == '\0' || icao3[1] == '\0' || icao3[2] == '\0') return NULL;

    /* Case-insensitive 3-char compare. The table is sorted ascending by
     * ICAO code (generator + manual additions both maintain this), so
     * a 3-byte lexicographic comparator drives a standard binary
     * search — ~10 comparisons worst case for 767 entries. */
    char k0 = (char)toupper((unsigned char)icao3[0]);
    char k1 = (char)toupper((unsigned char)icao3[1]);
    char k2 = (char)toupper((unsigned char)icao3[2]);

    int lo = 0;
    int hi = (int)S_AIRLINES_N - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        const char *e = s_airlines[mid].icao3;
        int cmp = (unsigned char)e[0] - (unsigned char)k0;
        if (cmp == 0) cmp = (unsigned char)e[1] - (unsigned char)k1;
        if (cmp == 0) cmp = (unsigned char)e[2] - (unsigned char)k2;
        if (cmp == 0) return &s_airlines[mid];
        if (cmp <  0) lo = mid + 1;
        else          hi = mid - 1;
    }
    return NULL;
}

const pk_airline_t *pk_airline_from_callsign(const char *callsign,
                                             const char **flight_number_out)
{
    if (flight_number_out) *flight_number_out = NULL;
    if (callsign == NULL || callsign[0] == '\0') return NULL;

    /* Callsign must start with 3 letters followed by at least 1
     * non-letter (typically digits). N12345 / D-EABC / RAF123 style
     * registrations / military bypass the airline table. */
    if (!isalpha((unsigned char)callsign[0]) ||
        !isalpha((unsigned char)callsign[1]) ||
        !isalpha((unsigned char)callsign[2])) {
        return NULL;
    }
    if (callsign[3] == '\0' || isalpha((unsigned char)callsign[3])) {
        /* All-letter callsign or only 3 chars — not an airline flight number */
        return NULL;
    }

    const pk_airline_t *a = pk_airline_from_icao3(callsign);
    if (a && flight_number_out) *flight_number_out = &callsign[3];
    return a;
}
