/* Generated by firmware/scripts/gen_i18n_assets.py. */
#pragma once

typedef enum {
    PK_LANG_EN = 0,
    PK_LANG_ZH = 1,
    PK_LANG_COUNT,
} pk_lang_t;

typedef enum {
    PK_TR_SETTINGS_TITLE = 0,
    PK_TR_SETTINGS_LANGUAGE = 1,
    PK_TR_LANG_ENGLISH = 2,
    PK_TR_LANG_CHINESE = 3,
    PK_TR_SETTINGS_FOOTER = 4,
    PK_TR_ABOUT_TITLE = 5,
    PK_TR_ABOUT_PROJECT = 6,
    PK_TR_ABOUT_VERSION = 7,
    PK_TR_ABOUT_BUILD = 8,
    PK_TR_ABOUT_IDF = 9,
    PK_TR_ABOUT_BOARD = 10,
    PK_TR_ABOUT_CHIP = 11,
    PK_TR_ABOUT_DISPLAY = 12,
    PK_TR_ABOUT_IMU = 13,
    PK_TR_ABOUT_DONGLE = 14,
    PK_TR_ABOUT_CAL = 15,
    PK_TR_ABOUT_HINT_CONVERGED = 16,
    PK_TR_ABOUT_HINT_CONVERGING = 17,
    PK_TR_ABOUT_HINT_FIG8 = 18,
    PK_TR_ABOUT_FOOTER = 19,
    PK_TR_CAL_TITLE = 20,
    PK_TR_CAL_LINE1 = 21,
    PK_TR_CAL_LINE2 = 22,
    PK_TR_CAL_QUALITY = 23,
    PK_TR_CAL_FOOTER = 24,
    PK_TR_COUNT,
} pk_tr_id_t;

const char *pk_i18n_catalog_text(pk_lang_t lang, pk_tr_id_t id);
