/* Generated by firmware/scripts/gen_i18n_assets.py. */
#include "i18n_catalog.h"

static const char *const s_text[PK_LANG_COUNT][PK_TR_COUNT] = {
    [PK_LANG_EN] = {
        [PK_TR_SETTINGS_TITLE] = "SETTINGS",
        [PK_TR_SETTINGS_LANGUAGE] = "Language",
        [PK_TR_LANG_ENGLISH] = "English",
        [PK_TR_LANG_CHINESE] = "Chinese",
        [PK_TR_SETTINGS_FOOTER] = "MODE page  UP/DOWN row  TARE change",
        [PK_TR_ABOUT_TITLE] = "ABOUT",
        [PK_TR_ABOUT_PROJECT] = "Project",
        [PK_TR_ABOUT_VERSION] = "Version",
        [PK_TR_ABOUT_BUILD] = "Build",
        [PK_TR_ABOUT_IDF] = "ESP-IDF",
        [PK_TR_ABOUT_BOARD] = "Board",
        [PK_TR_ABOUT_CHIP] = "Chip rev",
        [PK_TR_ABOUT_DISPLAY] = "Display",
        [PK_TR_ABOUT_IMU] = "IMU",
        [PK_TR_ABOUT_DONGLE] = "Dongle",
        [PK_TR_ABOUT_CAL] = "IMU cal",
        [PK_TR_ABOUT_HINT_CONVERGED] = "Fusion converged.",
        [PK_TR_ABOUT_HINT_CONVERGING] = "Converging - keep moving",
        [PK_TR_ABOUT_HINT_FIG8] = "Move in figure-8 to calibrate",
        [PK_TR_ABOUT_FOOTER] = "MODE cycle    UP/DOWN scroll",
        [PK_TR_CAL_TITLE] = "COMPASS CAL",
        [PK_TR_CAL_LINE1] = "Move device in a figure-8",
        [PK_TR_CAL_LINE2] = "rotating in all directions",
        [PK_TR_CAL_QUALITY] = "Quality",
        [PK_TR_CAL_FOOTER] = "Press MODE to skip",
        [PK_TR_TOAST_TARE_SAVED] = "Saved",
        [PK_TR_TOAST_TARE_SAVE_FAIL] = "Save failed",
        [PK_TR_TOAST_OWN_BOUND] = "Own set",
        [PK_TR_TOAST_OWN_CLEARED] = "Own cleared",
    },
    [PK_LANG_ZH] = {
        [PK_TR_SETTINGS_TITLE] = "设置",
        [PK_TR_SETTINGS_LANGUAGE] = "语言",
        [PK_TR_LANG_ENGLISH] = "英文",
        [PK_TR_LANG_CHINESE] = "中文",
        [PK_TR_SETTINGS_FOOTER] = "MODE 页  UP/DOWN 选  TARE 改",
        [PK_TR_ABOUT_TITLE] = "关于",
        [PK_TR_ABOUT_PROJECT] = "项目",
        [PK_TR_ABOUT_VERSION] = "版本",
        [PK_TR_ABOUT_BUILD] = "构建",
        [PK_TR_ABOUT_IDF] = "ESP-IDF",
        [PK_TR_ABOUT_BOARD] = "开发板",
        [PK_TR_ABOUT_CHIP] = "芯片",
        [PK_TR_ABOUT_DISPLAY] = "屏幕",
        [PK_TR_ABOUT_IMU] = "姿态",
        [PK_TR_ABOUT_DONGLE] = "接收机",
        [PK_TR_ABOUT_CAL] = "校准",
        [PK_TR_ABOUT_HINT_CONVERGED] = "融合已收敛",
        [PK_TR_ABOUT_HINT_CONVERGING] = "正在收敛 - 继续移动",
        [PK_TR_ABOUT_HINT_FIG8] = "画 8 字校准",
        [PK_TR_ABOUT_FOOTER] = "MODE 切换    UP/DOWN 滚动",
        [PK_TR_CAL_TITLE] = "罗盘校准",
        [PK_TR_CAL_LINE1] = "画 8 字移动设备",
        [PK_TR_CAL_LINE2] = "各方向旋转",
        [PK_TR_CAL_QUALITY] = "质量",
        [PK_TR_CAL_FOOTER] = "按 MODE 跳过",
        [PK_TR_TOAST_TARE_SAVED] = "已保存",
        [PK_TR_TOAST_TARE_SAVE_FAIL] = "保存失败",
        [PK_TR_TOAST_OWN_BOUND] = "已绑定本机",
        [PK_TR_TOAST_OWN_CLEARED] = "已取消本机",
    },
};

const char *pk_i18n_catalog_text(pk_lang_t lang, pk_tr_id_t id)
{
    if (lang < 0 || lang >= PK_LANG_COUNT) lang = PK_LANG_EN;
    if (id < 0 || id >= PK_TR_COUNT) return "?";
    const char *text = s_text[lang][id];
    return text ? text : s_text[PK_LANG_EN][id];
}
