/* Generated by firmware/scripts/gen_pfd_cockpit_font.py. */
#pragma once

#include <stdint.h>

#define PK_FONT_AA_CELL_W 12
#define PK_FONT_AA_CELL_H 16
#define PK_FONT_AA_GLYPH_BYTES ((PK_FONT_AA_CELL_W * PK_FONT_AA_CELL_H) / 2)

const uint8_t *pk_font_aa_glyph(unsigned code);
