/* Generated by firmware/scripts/gen_i18n_assets.py. */
#pragma once

#include <stdint.h>

#define PK_TEXT_CJK_BODY_CELL_W 8
#define PK_TEXT_CJK_BODY_CELL_H 8
#define PK_TEXT_CJK_BODY_GLYPH_BYTES 32

const uint8_t *pk_text_cjk_body_glyph(uint32_t code);
