M48
; DRILL file KiCad 10.0.4 date 2026-08-30T20:14:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-30T20:14:21+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X143.205Y-70.11
X143.205Y-75.89
T2
X54.0Y-56.0
X54.0Y-106.0
X146.0Y-56.0
X146.0Y-106.0
M30
